-- Create Feedback Table for Complaints & Suggestions
CREATE TABLE feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  type TEXT NOT NULL, -- 'complaint' or 'suggestion'
  category TEXT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  contact_email TEXT,
  status TEXT DEFAULT 'pending' -- 'pending', 'resolved', 'reviewed'
);

-- Enable Row Level Security (RLS)
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (anyone can complain)
CREATE POLICY "Allow anonymous inserts" ON feedback FOR INSERT WITH CHECK (true);

-- Create Messages Table for Chat
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  content TEXT NOT NULL,
  sender_role TEXT DEFAULT 'user' -- 'user' or 'admin'
);

-- Enable RLS
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts
CREATE POLICY "Allow anonymous inserts" ON messages FOR INSERT WITH CHECK (true);

-- Allow public read (so users can see chat history in this public channel demo)
CREATE POLICY "Allow public read" ON messages FOR SELECT USING (true);

-- Enable Realtime for messages
alter publication supabase_realtime add table messages;

-- --- NEW TABLES FOR ADMIN PORTAL ---

-- Committees Table
CREATE TABLE committees (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL, -- For cleaner URLs if needed
  icon_name TEXT DEFAULT 'Users', -- Store the Lucide icon name as string
  short_description TEXT,
  purpose TEXT,
  structure TEXT[], -- Array of strings
  roles TEXT[], -- Array of strings
  chairs TEXT[], -- Array of strings
  members TEXT[] -- Array of strings
);

-- Enable RLS for Committees
ALTER TABLE committees ENABLE ROW LEVEL SECURITY;

-- Allow public read (everyone sees committees)
CREATE POLICY "Allow public read committees" ON committees FOR SELECT USING (true);

-- Allow authenticated (admin) write
-- Note: You will need to setup Supabase Auth or use a service role key for admin writes in the app.
-- For this simple implementation using a shared password, we might use the service role key on the server side,
-- or strictly control the API endpoints.
-- For now, open insert/update for demonstration if simple auth is used, OR restrict to authenticated users.
CREATE POLICY "Allow admin insert committees" ON committees FOR INSERT WITH CHECK (true); 
CREATE POLICY "Allow admin update committees" ON committees FOR UPDATE USING (true);
CREATE POLICY "Allow admin delete committees" ON committees FOR DELETE USING (true);


-- Projects Table
CREATE TABLE projects (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT DEFAULT 'Ongoing', -- 'Ongoing', 'Completed', 'Upcoming'
  image_url TEXT,
  category TEXT
);

-- Enable RLS for Projects
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Allow public read
CREATE POLICY "Allow public read projects" ON projects FOR SELECT USING (true);

-- Allow admin write
CREATE POLICY "Allow admin insert projects" ON projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin update projects" ON projects FOR UPDATE USING (true);
CREATE POLICY "Allow admin delete projects" ON projects FOR DELETE USING (true);
