-- Create the feedback table
create table feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null, -- 'complaint' or 'suggestion'
  title text not null,
  description text not null,
  category text,
  contact_email text,
  status text default 'pending' -- 'pending', 'reviewed', 'resolved'
);

-- Enable RLS (Row Level Security)
alter table feedback enable row level security;

-- Create policy to allow anyone (anon) to insert feedback
create policy "Enable insert for everyone" on feedback
  for insert with check (true);

-- Create policy to allow only authenticated users (admins) to view feedback
create policy "Enable read for authenticated users only" on feedback
  for select using (auth.role() = 'authenticated');
